<?php require('_header.php'); ?>

<h2>Why use FirePHP?</h2>

<p>FirePHP enables the logging of PHP variables to a browser devtools panel.<br/>
As a page loads in the browser the devtools panel
fills with log messages generated by all PHP requests involved in generating the page.</p>

<p>PHP code is instrumented with <a href="/api.php">FirePHP API</a> calls to log variables for ad hoc debugging purposes or to provide general insight accessible all the time.</p>

<h2>Client Extension Setup</h2>

<ol>
    <li>
        <p><b>Install Browser Extension</b> for your browser from the <a href="/">home</a> page and follow the instructions below.<br/>
        We are going to first inspect some example messages generate by this page.</p>
    </li>
    <li>
        <p><b>Give FirePHP permission</b> to intercept requests for the page in order to get access to request and response headers.</p>

        <h3>Firefox</h3>

        <p>Click on the gray FirePHP icon on the right of the address bar. Then click the grant checkbox.</p>

        <p><img src="/resources/images/quickstart-firefox-give-permission.png" border="0"></p>

        <h3>Google Chrome</h3>

        <p>Click on the extensions menu and then the FirePHP extension. After, click on new FirePHP icon that just appeared. Then click the grant checkbox.</p>

        <p><img src="/resources/images/quickstart-chrome-give-permission.png" border="0"></p>
        <p><img src="/resources/images/quickstart-chrome-give-permission2.png" border="0"></p>

    </li>
    <li>
        <p><b>Open Devtools and enable protocol</b> to tell the extension to send the appropriate request headers and look for specific reponse headers.</p>

        <p>Open devtools, click on the FirePHP devtools tab and then click one of the <i>FirePHP (Wildfire based) Protocol</i> checkboxes.</p>

        <p>This will complete the setup for the hostname.</p>

        <p><img src="/resources/images/quickstart-devtools-settings.png" border="0"></p>
    </li>
    <li>
        <p><b>Enable logging</b> for this page.</p>

        <p>Click on the <i>Click to Enable</i> button and the browser page should reload.</p>
        <p>If the page does not reload, reload the browser page yourself.</p>

        <p><img src="/resources/images/quickstart-devtools-enable.png" border="0"></p>
    </li>
    <li>
        <p><b>Instect logs</b></p>

        <p>You should see log messages generated by the PHP script that generated this page. See blow for how these messages were generated.</p>

        <p>If no log messages show up, reload the browser page again.</p>

        <p><img src="/resources/images/quickstart-devtools-logs.png" border="0"></p>
    </li>
</ol>

<h2>Server Library Setup</h2>

<p><i>TODO</i></p>

<h2>Local Development</h2>

<p><i>TODO</i></p>

<h2>Production Release</h2>

<p><i>TODO</i></p>

<?php require('_footer.php'); ?>
